export const DummyData = [
  {
    id: 0,
    // image: appIcons.user2,
    name: 'Mark Smith',
    time: '10 min',
    commentCount: 10,
    likeCount: 10,
    faqDetail: `How this app works`,
    // notificationImage: appIcons.user2,
    // cardImage: appIcons.moon,
    feeling: 'Excited',

    description: `Lorem Ipsum is dolor sit amet, consectetur adipisoing elit |`,
  },
  {
    id: 1,
    // image: appIcons.user1,
    name: 'Lisa Marie',
    time: '10 min',
    commentCount: 10,
    likeCount: 10,
    topic: 'Scary Dream',
    feeling: 'Anxious',
    type: 'Challenge',
    faqDetail: `FAQ number 01`,
    description: `Lorem Ipsum is dolor sit amet, consectetur adipisoing elit |`,
    // notificationImage: appIcons.user1,
    // cardImage: appIcons.sun,
  },
  {
    id: 2,
    // image: appIcons.user2,
    name: 'Bella Jane',
    time: '1 hour',
    commentCount: 10,
    likeCount: 10,

    feeling: 'Worried',
    type: 'Action',
    faqDetail: `FAQ number 02`,
    description: `Lorem Ipsum is dolor sit amet, consectetur adipisoing elit|`,
    // notificationImage: appIcons.user3,
    // cardImage: appIcons.moon,
  },
  {
    id: 3,
    // image: appIcons.user1,
    name: 'Jane Arjun',
    time: '8 hour',
    commentCount: 10,
    likeCount: 10,

    feeling: 'Energized',
    type: 'Fashion',
    faqDetail: `FAQ number 03`,
    // notificationImage: appIcons.user4,
    // cardImage: appIcons.sun,
    description: `Lorem Ipsum is dolor sit amet, consectetur adipisoing elit |`,
  },
  {
    id: 4,
    // image: appIcons.user2,
    name: 'Messi Bella',
    time: '9 hour',
    commentCount: 10,
    likeCount: 10,


    type: 'Shopping',
    faqDetail: `FAQ number 04`,
    description: `Lorem Ipsum is dolor sit amet, consectetur adipisoing elit |`,
    // notificationImage: appIcons.user5,
    // cardImage: appIcons.moon,
  },
  {
    id: 5,
    // image: appIcons.user1,
    name: 'John Smith',
    time: '1 hour',
    commentCount: 10,
    likeCount: 10,
    faqDetail: `FAQ number 05`,
    topic: 'Lucid Dream',

    type: 'Expression',
    // notificationImage: appIcons.user6,
    // cardImage: appIcons.sun,
    description: `Lorem Ipsum is dolor sit amet, consectetur adipisoing elit |`,
  },
];